// @littlesheep/memory-tree — public API

export {
  InjectionTier,
  type MemoryFragment,
  type MemoryBranchAccessObservation,
  type MemoryIndexEntry,
  type BranchIndex,
  type BranchExpansion,
  type BranchExpandRequest,
  type BranchSearchRequest,
  type MemoryBranchContext,
  type MemoryBranch,
  type BranchDescription,
  type MemoryTreeOptions,
  type MemoryRunRegistration,
  type MemoryAccessRecord,
  type MemoryAccessLedger,
  type MemoryRunFeedbackInput,
  type MemoryExpandOptions,
  type MemorySearchOptions,
  type MemoryQueryResult,
  type MemoryBranchKind,
  type MemoryBranchCategory,
  type MemoryScope,
  type MemoryResourceScope,
  type MemoryResourceKind,
  type MemoryResourceAuthority,
  type MemoryResourcePrivacy,
  type MemoryResourceStatus,
  type MemoryResourceSourceKind,
  type MemoryResourceSource,
  type MemoryResourceRegistration,
  type MemoryResourceQuery,
  type MemoryResourceManagementAction,
  type MemoryResourceManagementActor,
  type MemoryResourceOwnerKind,
  type MemoryResourceLifecycleController,
  type MemoryResourceOwner,
  type MemoryResourceManagementAuditRecord,
  type MemoryResourceManagementResult,
  type MemoryResourceRebindPatch,
  type MemoryWriteIntent,
  type MemoryNode,
  type MemoryRecentNodeQuery,
  type MemoryNodeStatus,
  type MemoryManagementAction,
  type MemoryManagementAuditRecord,
  type MemoryManagementResult,
  type MemoryMigrationRecord,
  type MemorySchemaMigrationRecord,
  type MemoryTreeDocument,
  type MemoryTreeDocumentV1,
  type MemoryWritePolicy,
  type MemoryWriteResult,
  type LogFn,
  type ProjectEntry,
  type ProjectIndex,
  type GitLogEntry,
} from './types.js';
export { MemoryTree } from './memory-tree.js';
export {
  composeMemoryTaskQuery,
  type MemoryTaskContinuitySummary,
  type MemoryTaskQuery,
  type MemoryTaskQueryHistoryMessage,
  type MemoryTaskQueryLimits,
  type MemoryTaskQuerySegment,
  type MemoryTaskQuerySegmentSource,
  type MemoryTaskReferenceKind,
} from './task-query.js';
export {
  scoreMemoryTaskRelevance,
  describeMemoryTaskRelevance,
  type MemoryTaskRelevanceDocument,
  type MemoryTaskRelevanceField,
  type MemoryTaskRelevanceResult,
} from './task-relevance.js';
export {
  MemoryResourceBranch,
  type MemoryResourceBranchOptions,
  type MemoryResourceResolver,
  type ResolvedMemoryResourceContent,
} from './memory-resource-branch.js';
export { ProjectMemoryBranch, type ProjectMemoryBranchDeps } from './project-memory-branch.js';
export {
  ProjectMemoryProjectionService,
  projectProjectionResourceId,
  projectProjectionRegistryGroup,
  type ProjectMemoryTarget,
  type ProjectMemoryProjectionEntry,
  type ProjectMemoryPrivateProjection,
  type ProjectMemoryProjectionStatus,
  type ProjectMemoryProjectionState,
  type ProjectMemoryShareableExportResult,
  type ProjectMemoryProjectionServiceOptions,
} from './project-memory-projection.js';
export { TreeMemoryBranch, DEFAULT_BRANCH_SPECS, type TreeMemoryBranchOptions } from './tree-memory-branch.js';
export { CompositeMemoryBranch, type CompositeMemoryBranchOptions } from './composite-memory-branch.js';
export {
  LegacyLongTermBranch,
  LegacyDailyBranch,
  LegacyExperienceBranch,
  SemanticDailyBranch,
  LEGACY_MEMORY_MIGRATION_ID,
  migrateLegacyMemorySources,
  type ExperienceStoreLike,
  type VectorMemorySearchLike,
  type LegacyMemoryMigrationOptions,
  type LegacyMemoryMigrationResult,
} from './legacy-memory-branches.js';
export {
  MemoryRepository,
  MemoryWriteService,
  createMemoryV3ExperimentMarker,
  MEMORY_V3_EXPERIMENT_MARKER,
  type MemoryRepositoryOptions,
  type MemoryRepositoryBackendKind,
  type MemoryV3ExperimentMarker,
  type ReplaceMemoryResourceGroupOptions,
  type ManageMemoryResourceOptions,
  type RebindMemoryResourceOptions,
  type RemoveMemoryResourcesOptions,
  type MemoryWriteServiceOptions,
  type MemoryWriteServiceLike,
} from './memory-repository.js';
export type {
  MemoryAtomManagementAudit,
  MemoryAtomManagementRequest,
  MemoryAtomManagementResult,
  MemoryAtomRevisionPatch,
  MemoryRepositoryEmbeddingStatusCounts,
  MemoryRepositoryManagementFacade,
  MemoryRepositoryManagementStatus,
  MemoryRepositoryNodeInspection,
} from './memory-repository/management.js';
export {
  MEMORY_REPOSITORY_LOCATOR_FILE,
  memoryRepositoryLocatorPath,
  readMemoryRepositoryLocator,
  type CompletedMemoryV3Migration,
  type MemoryRepositoryLocator,
  type MemoryV3MigrationPhase,
  type MemoryV3RollbackPhase,
  type PendingMemoryV3Migration,
  type PendingMemoryV3Rollback,
} from './memory-repository/repository-locator.js';
export {
  MemoryV2ToV3MigrationManager,
  type MemoryV2ToV3MigrationManagerOptions,
  type MemoryV3BootstrapPreparation,
  type MemoryV3MigrationFaultContext,
  type MemoryV3MigrationFaultPoint,
  type MemoryV3MigrationPreflight,
  type MemoryV3MigrationResult,
  type MemoryV3MigrationValidation,
  type MemoryV3PreflightOptions,
  type MemoryV3RollbackReadiness,
  type PrepareMemoryV3ForBootstrapOptions,
} from './memory-repository/v3-migration.js';
export {
  MemoryService,
  attachmentManifestResourceId,
  attachmentResourceId,
  runtimeEventLedgerResourceId,
  type MemoryServiceOptions,
  type MemoryRunStart,
  type MemoryRunRefinement,
  type MemoryRunRefinementInput,
  type MemoryRunRefinementServiceLike,
  type MemoryRunResourceInput,
  type MemoryManagementSnapshot,
  type MemorySkillResourceInput,
  type MemorySkillSourceInput,
  type SyncMemorySkillResourcesOptions,
  type MemoryNavigationServiceLike,
  type MemoryBootstrapServiceLike,
} from './memory-service.js';
export {
  createMemoryTreeTool,
  createMemorySearchCompatibilityTool,
  createMemoryDeepSearchCompatibilityTool,
  type MemoryToolOptions,
} from './memory-tool.js';
export { fetchGitLog, fetchLatestCommitDate, parseGitLog } from './git-log.js';
export { readProjectIndex } from './project-index.js';
export {
  WorkspaceResourceIndexStore,
  type WorkspaceResourceIndexStoreOptions,
  type WorkspaceResourceIndexLimits,
  type WorkspaceBoundaryKind,
  type WorkspaceIndexedFileOwner,
  type WorkspaceIndexedFileKind,
  type WorkspaceResourceChange,
  type WorkspaceResourceSyncOptions,
  type WorkspaceIndexedFile,
  type WorkspaceResourceScanState,
  type WorkspaceResourceIndexSnapshot,
  type WorkspaceResourceSyncResult,
} from './workspace-resource-index.js';
export { estimateTokens, activityScore, truncateChunk, MIN_USEFUL_TOKENS } from './util.js';
export { memoryUseFeedbackFromRun } from './memory-feedback.js';
export {
  MemoryDailyConsolidationService,
  type MemoryDailyConsolidationFailure,
  type MemoryDailyConsolidationInput,
  type MemoryDailyConsolidationResult,
  type MemoryDailyConsolidationServiceOptions,
} from './memory-consolidation.js';
export {
  MemoryAtomReconciliationService,
  type MemoryAtomMergeProposal,
  type MemoryAtomReconciliationProposal,
  type MemoryAtomReconciliationResult,
  type MemoryAtomReconciliationServiceLike,
  type MemoryAtomReconciliationServiceOptions,
  type MemoryAtomReconciliationStatus,
  type MemoryAtomRevisionReference,
} from './memory-reconciliation.js';
export {
  MemoryAtomHierarchyService,
  type MemoryAtomHierarchyResult,
  type MemoryAtomHierarchyServiceLike,
  type MemoryAtomHierarchyServiceOptions,
  type MemoryAtomHierarchyStatus,
  type MemoryAtomReparentProposal,
} from './memory-hierarchy.js';
export {
  MAX_SUBTREE_ACTIVE_DESCENDANTS,
  MAX_SUBTREE_PROPOSALS,
  MemoryAtomSubtreeService,
  type MemoryAtomSubtreeMoveProposal,
  type MemoryAtomSubtreeResult,
  type MemoryAtomSubtreeServiceLike,
  type MemoryAtomSubtreeServiceOptions,
  type MemoryAtomSubtreeStatus,
} from './memory-subtree.js';
export {
  MAX_REVISION_PROPOSALS,
  MemoryAtomRevisionService,
  type MemoryAtomRevisionProposal,
  type MemoryAtomRevisionResult,
  type MemoryAtomRevisionServiceLike,
  type MemoryAtomRevisionStatus,
} from './memory-revision.js';
export {
  MAX_CORRECTION_PROPOSALS,
  MemoryAtomCorrectionService,
  type MemoryAtomCorrectionBasis,
  type MemoryAtomCorrectionProposal,
  type MemoryAtomCorrectionResult,
  type MemoryAtomCorrectionServiceLike,
  type MemoryAtomCorrectionStatus,
} from './memory-correction.js';
export {
  MemoryConversationSourceStore,
  MemoryConversationSourceConflictError,
  MEMORY_CONVERSATION_SOURCE_VERSION,
} from './conversation-source-store.js';
export type {
  MemoryConversationSourceInput,
  MemoryConversationSourceKind,
  MemoryConversationSourceManifest,
  MemoryConversationSourceRecord,
} from './conversation-source-store.js';
export * as MemoryV3 from './v3/index.js';
export type {
  AuthorityKind,
  AuthorityScope,
  EpistemicStatus,
  MemoryActorKind,
  MemoryActorRef,
  MemoryAuthorityScope,
  MemoryDomain,
  MemoryEntityType,
  MemoryRelationType,
  MemoryWriteEntityHint,
  MemoryWriteEpistemicMetadata,
  MemoryWriteRelationHint,
  StatementKind,
} from './epistemic.js';
export {
  MemoryAtomStore,
  MemoryAtomConflictError,
  MemoryCatalog,
  DisabledEmbeddingEngine,
  EmbeddingUnavailableError,
  MemoryEventJournal,
  MemoryRawRecordStore,
  MemoryRawRecordStore as MemoryProjectionMutationRecordStore,
  MemoryRawRecordConflictError,
  MemoryRawRecordCommitConflictError,
  MemoryOperationJournal,
  MemoryV3MaintenanceWorker,
  MemoryV3StorageCoordinator,
  scoreMemoryCandidate,
} from './v3/index.js';
export type {
  MemoryAtom as MemoryAtomV3,
  MemoryAtomInvalidation,
  MemoryAtomMerge,
  MemoryAtomSupersession,
  MemoryProjectionMutationRecord,
  MemoryProjectionMutationCommitReceipt,
  MemoryRawRecord,
  MemoryRawRecordCommitReceipt,
  MemoryCatalogEntry as MemoryCatalogEntryV3,
  MemoryDisclosureLevel,
  MemoryEntity,
  MemoryRelation,
  MemoryUpdateEvent,
  MemoryUseFeedback,
  MemoryEvidenceEnvelope,
  KnownStateMemoryReference,
  MemoryKnownState,
  KnownStateMemoryDecision,
  MemoryRelationNeighborhood,
  MemoryAtomHistory,
  EmbeddingEngine,
  EmbeddingEngineDescriptor,
  EmbeddingRequest,
  EmbeddingResult,
} from './v3/index.js';
