// @littlesheep/memory-tree — public API

export {
  InjectionTier,
  type MemoryFragment,
  type MemoryBranchAccessObservation,
  type MemoryIndexEntry,
  type BranchIndex,
  type BranchExpansion,
  type BranchExpandRequest,
  type BranchSearchRequest,
  type MemoryBranchContext,
  type MemoryBranch,
  type BranchDescription,
  type MemoryTreeOptions,
  type MemoryRunRegistration,
  type MemoryAccessRecord,
  type MemoryAccessLedger,
  type MemoryExpandOptions,
  type MemorySearchOptions,
  type MemoryQueryResult,
  type MemoryBranchKind,
  type MemoryBranchCategory,
  type MemoryScope,
  type MemoryResourceScope,
  type MemoryResourceKind,
  type MemoryResourceAuthority,
  type MemoryResourcePrivacy,
  type MemoryResourceStatus,
  type MemoryResourceSourceKind,
  type MemoryResourceSource,
  type MemoryResourceRegistration,
  type MemoryResourceQuery,
  type MemoryResourceManagementAction,
  type MemoryResourceManagementActor,
  type MemoryResourceOwnerKind,
  type MemoryResourceLifecycleController,
  type MemoryResourceOwner,
  type MemoryResourceManagementAuditRecord,
  type MemoryResourceManagementResult,
  type MemoryResourceRebindPatch,
  type MemoryWriteIntent,
  type MemoryNode,
  type MemoryNodeStatus,
  type MemoryManagementAction,
  type MemoryManagementAuditRecord,
  type MemoryManagementResult,
  type MemoryMigrationRecord,
  type MemorySchemaMigrationRecord,
  type MemoryTreeDocument,
  type MemoryTreeDocumentV1,
  type MemoryWritePolicy,
  type MemoryWriteResult,
  type LogFn,
  type ProjectEntry,
  type ProjectIndex,
  type GitLogEntry,
} from './types.js';
export { MemoryTree } from './memory-tree.js';
export {
  MemoryResourceBranch,
  type MemoryResourceBranchOptions,
  type MemoryResourceResolver,
  type ResolvedMemoryResourceContent,
} from './memory-resource-branch.js';
export { ProjectMemoryBranch, type ProjectMemoryBranchDeps } from './project-memory-branch.js';
export {
  ProjectMemoryProjectionService,
  projectProjectionResourceId,
  projectProjectionRegistryGroup,
  type ProjectMemoryTarget,
  type ProjectMemoryProjectionEntry,
  type ProjectMemoryPrivateProjection,
  type ProjectMemoryProjectionStatus,
  type ProjectMemoryProjectionState,
  type ProjectMemoryShareableExportResult,
  type ProjectMemoryProjectionServiceOptions,
} from './project-memory-projection.js';
export { TreeMemoryBranch, DEFAULT_BRANCH_SPECS, type TreeMemoryBranchOptions } from './tree-memory-branch.js';
export { CompositeMemoryBranch, type CompositeMemoryBranchOptions } from './composite-memory-branch.js';
export {
  LegacyLongTermBranch,
  LegacyDailyBranch,
  LegacyExperienceBranch,
  SemanticDailyBranch,
  LEGACY_MEMORY_MIGRATION_ID,
  migrateLegacyMemorySources,
  type ExperienceStoreLike,
  type VectorMemorySearchLike,
  type LegacyMemoryMigrationOptions,
  type LegacyMemoryMigrationResult,
} from './legacy-memory-branches.js';
export {
  MemoryRepository,
  MemoryWriteService,
  createMemoryV3ExperimentMarker,
  MEMORY_V3_EXPERIMENT_MARKER,
  type MemoryRepositoryOptions,
  type MemoryRepositoryBackendKind,
  type MemoryV3ExperimentMarker,
  type ReplaceMemoryResourceGroupOptions,
  type ManageMemoryResourceOptions,
  type RebindMemoryResourceOptions,
  type RemoveMemoryResourcesOptions,
  type MemoryWriteServiceOptions,
  type MemoryWriteServiceLike,
} from './memory-repository.js';
export type {
  MemoryRepositoryEmbeddingStatusCounts,
  MemoryRepositoryManagementFacade,
  MemoryRepositoryManagementStatus,
  MemoryRepositoryNodeInspection,
} from './memory-repository/management.js';
export {
  MEMORY_REPOSITORY_LOCATOR_FILE,
  memoryRepositoryLocatorPath,
  readMemoryRepositoryLocator,
  type CompletedMemoryV3Migration,
  type MemoryRepositoryLocator,
  type MemoryV3MigrationPhase,
  type PendingMemoryV3Migration,
} from './memory-repository/repository-locator.js';
export {
  MemoryV2ToV3MigrationManager,
  type MemoryV2ToV3MigrationManagerOptions,
  type MemoryV3MigrationFaultContext,
  type MemoryV3MigrationFaultPoint,
  type MemoryV3MigrationPreflight,
  type MemoryV3MigrationResult,
} from './memory-repository/v3-migration.js';
export {
  MemoryService,
  attachmentManifestResourceId,
  attachmentResourceId,
  runtimeEventLedgerResourceId,
  type MemoryServiceOptions,
  type MemoryRunStart,
  type MemoryRunResourceInput,
  type MemoryManagementSnapshot,
  type MemorySkillResourceInput,
  type MemorySkillSourceInput,
  type SyncMemorySkillResourcesOptions,
  type MemoryNavigationServiceLike,
  type MemoryBootstrapServiceLike,
} from './memory-service.js';
export {
  createMemoryTreeTool,
  createMemorySearchCompatibilityTool,
  createMemoryDeepSearchCompatibilityTool,
  type MemoryToolOptions,
} from './memory-tool.js';
export { fetchGitLog, fetchLatestCommitDate, parseGitLog } from './git-log.js';
export { readProjectIndex } from './project-index.js';
export {
  WorkspaceResourceIndexStore,
  type WorkspaceResourceIndexStoreOptions,
  type WorkspaceResourceIndexLimits,
  type WorkspaceBoundaryKind,
  type WorkspaceIndexedFileOwner,
  type WorkspaceIndexedFileKind,
  type WorkspaceResourceChange,
  type WorkspaceResourceSyncOptions,
  type WorkspaceIndexedFile,
  type WorkspaceResourceScanState,
  type WorkspaceResourceIndexSnapshot,
  type WorkspaceResourceSyncResult,
} from './workspace-resource-index.js';
export { estimateTokens, activityScore, truncateChunk, MIN_USEFUL_TOKENS } from './util.js';
export * as MemoryV3 from './v3/index.js';
export type {
  AuthorityKind,
  AuthorityScope,
  EpistemicStatus,
  MemoryActorKind,
  MemoryActorRef,
  MemoryAuthorityScope,
  MemoryDomain,
  MemoryWriteEpistemicMetadata,
  StatementKind,
} from './epistemic.js';
export {
  MemoryAtomStore,
  MemoryAtomConflictError,
  MemoryCatalog,
  DisabledEmbeddingEngine,
  EmbeddingUnavailableError,
  MemoryEventJournal,
  MemoryOperationJournal,
  MemoryV3MaintenanceWorker,
  MemoryV3StorageCoordinator,
  scoreMemoryCandidate,
} from './v3/index.js';
export type {
  MemoryAtom as MemoryAtomV3,
  MemoryCatalogEntry as MemoryCatalogEntryV3,
  MemoryDisclosureLevel,
  MemoryEntity,
  MemoryRelation,
  MemoryUpdateEvent,
  MemoryUseFeedback,
  MemoryEvidenceEnvelope,
  KnownStateMemoryReference,
  MemoryKnownState,
  KnownStateMemoryDecision,
  MemoryRelationNeighborhood,
  MemoryAtomHistory,
  EmbeddingEngine,
  EmbeddingEngineDescriptor,
  EmbeddingRequest,
  EmbeddingResult,
} from './v3/index.js';
