// Shared workspace language registry.
// Keep file routing independent from Monaco's package-specific aliases.

export const MONACO_BUILTIN_LANGUAGE_IDS = new Set([
  'abap', 'apex', 'azcli', 'bat', 'bicep', 'cameligo', 'clojure', 'coffee',
  'cpp', 'csharp', 'csp', 'css', 'cypher', 'dart', 'dockerfile', 'ecl',
  'elixir', 'flow9', 'freemarker2', 'fsharp', 'go', 'graphql', 'handlebars',
  'hcl', 'html', 'ini', 'java', 'javascript', 'julia', 'json', 'kotlin', 'less',
  'lexon', 'liquid', 'lua', 'm3', 'markdown', 'mdx', 'mips', 'msdax', 'mysql',
  'objective-c', 'pascal', 'pascaligo', 'perl', 'pgsql', 'php', 'pla',
  'postiats', 'powerquery', 'powershell', 'protobuf', 'pug', 'python', 'qsharp',
  'r', 'razor', 'redis', 'redshift', 'restructuredtext', 'ruby', 'rust', 'sb',
  'scala', 'scheme', 'scss', 'shell', 'solidity', 'sophia', 'sparql', 'sql',
  'st', 'swift', 'systemverilog', 'tcl', 'twig', 'typescript', 'typespec', 'vb',
  'wgsl', 'xml', 'yaml',
])

// These IDs are registered by the renderer with a small, deterministic
// Monarch tokenizer when Monaco does not ship a language contribution.
export const LS_CUSTOM_LANGUAGE_IDS = new Set([
  'assembly', 'erlang', 'groovy', 'haskell', 'latex', 'nim', 'nix', 'ocaml', 'prisma', 'toml',
])

export const WORKSPACE_LANGUAGE_IDS = new Set([
  ...MONACO_BUILTIN_LANGUAGE_IDS,
  ...LS_CUSTOM_LANGUAGE_IDS,
  'plaintext',
])

const FILE_NAME_LANGUAGE_ALIASES: ReadonlyMap<string, string> = new Map([
  ['dockerfile', 'dockerfile'],
  ['containerfile', 'dockerfile'],
  ['makefile', 'shell'],
  ['justfile', 'shell'],
  ['cmakelists.txt', 'cpp'],
  ['go.mod', 'go'],
  ['go.sum', 'plaintext'],
  ['.editorconfig', 'ini'],
  ['.prettierrc', 'json'],
  ['.eslintrc', 'json'],
  ['.babelrc', 'json'],
  ['.stylelintrc', 'json'],
  ['.browserslistrc', 'plaintext'],
  ['compose.yaml', 'yaml'],
  ['compose.yml', 'yaml'],
  ['docker-compose.yaml', 'yaml'],
  ['docker-compose.yml', 'yaml'],
  ['jenkinsfile', 'groovy'],
  ['gemfile', 'ruby'],
  ['rakefile', 'ruby'],
  ['procfile', 'shell'],
  ['earthfile', 'shell'],
  ['vagrantfile', 'ruby'],
  ['brewfile', 'ruby'],
  ['pipfile', 'toml'],
  ['poetry.lock', 'toml'],
  ['cargo.lock', 'toml'],
])

const EXTENSION_LANGUAGE_ALIASES: ReadonlyMap<string, string> = new Map([
  ['.asm', 'assembly'],
  ['.s', 'assembly'],
  ['.bicep', 'bicep'],
  ['.bat', 'bat'],
  ['.cmd', 'bat'],
  ['.c', 'cpp'],
  ['.cc', 'cpp'],
  ['.cpp', 'cpp'],
  ['.cxx', 'cpp'],
  ['.h', 'cpp'],
  ['.hh', 'cpp'],
  ['.hpp', 'cpp'],
  ['.hxx', 'cpp'],
  ['.ipp', 'cpp'],
  ['.cs', 'csharp'],
  ['.csx', 'csharp'],
  ['.cshtml', 'razor'],
  ['.razor', 'razor'],
  ['.css', 'css'],
  ['.scss', 'scss'],
  ['.less', 'less'],
  ['.dart', 'dart'],
  ['.dockerfile', 'dockerfile'],
  ['.ex', 'elixir'],
  ['.exs', 'elixir'],
  ['.erl', 'erlang'],
  ['.hrl', 'erlang'],
  ['.fs', 'fsharp'],
  ['.fsi', 'fsharp'],
  ['.fsx', 'fsharp'],
  ['.fsscript', 'fsharp'],
  ['.go', 'go'],
  ['.graphql', 'graphql'],
  ['.gql', 'graphql'],
  ['.hcl', 'hcl'],
  ['.tf', 'hcl'],
  ['.tfvars', 'hcl'],
  ['.hs', 'haskell'],
  ['.lhs', 'haskell'],
  ['.html', 'html'],
  ['.htm', 'html'],
  ['.xhtml', 'html'],
  ['.ini', 'ini'],
  ['.cfg', 'ini'],
  ['.conf', 'ini'],
  ['.properties', 'ini'],
  ['.toml', 'toml'],
  ['.java', 'java'],
  ['.gradle', 'groovy'],
  ['.groovy', 'groovy'],
  ['.gvy', 'groovy'],
  ['.js', 'javascript'],
  ['.jsx', 'javascript'],
  ['.mjs', 'javascript'],
  ['.cjs', 'javascript'],
  ['.json', 'json'],
  ['.jsonc', 'json'],
  ['.json5', 'json'],
  ['.code-workspace', 'json'],
  ['.ipynb', 'json'],
  ['.jl', 'julia'],
  ['.kt', 'kotlin'],
  ['.kts', 'kotlin'],
  ['.lua', 'lua'],
  ['.md', 'markdown'],
  ['.markdown', 'markdown'],
  ['.mdx', 'mdx'],
  ['.m', 'objective-c'],
  ['.mm', 'objective-c'],
  ['.ml', 'ocaml'],
  ['.mli', 'ocaml'],
  ['.nim', 'nim'],
  ['.nix', 'nix'],
  ['.pas', 'pascal'],
  ['.pp', 'pascal'],
  ['.pl', 'perl'],
  ['.pm', 'perl'],
  ['.t', 'perl'],
  ['.php', 'php'],
  ['.phtml', 'php'],
  ['.prisma', 'prisma'],
  ['.proto', 'protobuf'],
  ['.ps1', 'powershell'],
  ['.psm1', 'powershell'],
  ['.psd1', 'powershell'],
  ['.ps1xml', 'powershell'],
  ['.py', 'python'],
  ['.pyw', 'python'],
  ['.pyi', 'python'],
  ['.r', 'r'],
  ['.rb', 'ruby'],
  ['.rake', 'ruby'],
  ['.gemspec', 'ruby'],
  ['.rs', 'rust'],
  ['.scala', 'scala'],
  ['.sc', 'scala'],
  ['.clj', 'clojure'],
  ['.cljs', 'clojure'],
  ['.cljc', 'clojure'],
  ['.edn', 'clojure'],
  ['.sh', 'shell'],
  ['.bash', 'shell'],
  ['.zsh', 'shell'],
  ['.fish', 'shell'],
  ['.sol', 'solidity'],
  ['.sql', 'sql'],
  ['.svelte', 'html'],
  ['.svg', 'xml'],
  ['.swift', 'swift'],
  ['.sv', 'systemverilog'],
  ['.svh', 'systemverilog'],
  ['.v', 'systemverilog'],
  ['.vh', 'systemverilog'],
  ['.tcl', 'tcl'],
  ['.tex', 'latex'],
  ['.tsx', 'typescript'],
  ['.ts', 'typescript'],
  ['.mts', 'typescript'],
  ['.cts', 'typescript'],
  ['.vb', 'vb'],
  ['.vbs', 'vb'],
  ['.vue', 'html'],
  ['.astro', 'html'],
  ['.xml', 'xml'],
  ['.xaml', 'xml'],
  ['.yaml', 'yaml'],
  ['.yml', 'yaml'],
])

export function workspaceLanguageForFile(lowerName: string, ext: string): string {
  const fileName = lowerName.trim().toLocaleLowerCase('en-US')
  const normalizedExt = normalizeExtension(ext)
  const language = FILE_NAME_LANGUAGE_ALIASES.get(fileName)
    ?? EXTENSION_LANGUAGE_ALIASES.get(normalizedExt)
  return language && WORKSPACE_LANGUAGE_IDS.has(language) ? language : 'plaintext'
}

export function normalizeWorkspaceLanguageId(language: string | undefined): string {
  const normalized = language?.trim().toLocaleLowerCase('en-US') ?? ''
  return WORKSPACE_LANGUAGE_IDS.has(normalized) ? normalized : 'plaintext'
}

export function normalizeExtension(ext: string): string {
  const normalized = ext.trim().toLocaleLowerCase('en-US')
  if (!normalized) return ''
  return normalized.startsWith('.') ? normalized : `.${normalized}`
}

export function workspaceLanguageLabel(language: string | undefined): string {
  const labels: Record<string, string> = {
    assembly: 'Assembly',
    bat: 'Batch',
    clojure: 'Clojure',
    cpp: 'C/C++',
    csharp: 'C#',
    css: 'CSS',
    dockerfile: 'Dockerfile',
    elixir: 'Elixir',
    erlang: 'Erlang',
    fsharp: 'F#',
    graphql: 'GraphQL',
    groovy: 'Groovy',
    handlebars: 'Handlebars',
    haskell: 'Haskell',
    hcl: 'HCL',
    html: 'HTML',
    ini: 'INI',
    javascript: 'JavaScript',
    json: 'JSON',
    julia: 'Julia',
    kotlin: 'Kotlin',
    latex: 'LaTeX',
    markdown: 'Markdown',
    nim: 'Nim',
    nix: 'Nix',
    'objective-c': 'Objective-C',
    ocaml: 'OCaml',
    perl: 'Perl',
    php: 'PHP',
    plaintext: 'Text',
    powershell: 'PowerShell',
    prisma: 'Prisma',
    protobuf: 'Protocol Buffers',
    python: 'Python',
    r: 'R',
    ruby: 'Ruby',
    rust: 'Rust',
    scala: 'Scala',
    shell: 'Shell',
    solidity: 'Solidity',
    sql: 'SQL',
    swift: 'Swift',
    systemverilog: 'SystemVerilog',
    typescript: 'TypeScript',
    vb: 'Visual Basic',
    xml: 'XML',
    yaml: 'YAML',
  }
  const normalized = normalizeWorkspaceLanguageId(language)
  return labels[normalized] ?? normalized
}
