// @littlesheep/app - workspace-file-routing.ts
// Pure workspace file routing helpers shared by the Local App API and tests.

import { workspaceLanguageForFile } from '../shared/workspace-languages.js'

export type WorkspaceFileSurface =
  | 'builtinEditor'
  | 'imagePreview'
  | 'pdfPreview'
  | 'documentCard'
  | 'sniffText'

export const WORKSPACE_MARKDOWN_EXTS = new Set(['.md', '.markdown', '.mdx'])
export const WORKSPACE_IMAGE_EXTS = new Set(['.png', '.jpg', '.jpeg', '.gif', '.webp', '.bmp', '.tiff', '.svg'])
export const WORKSPACE_PDF_EXTS = new Set(['.pdf'])
export const WORKSPACE_OFFICE_EXTS = new Set([
  '.doc',
  '.docx',
  '.docm',
  '.dot',
  '.dotx',
  '.ppt',
  '.pptx',
  '.pptm',
  '.pps',
  '.ppsx',
  '.pot',
  '.potx',
  '.xls',
  '.xlsx',
  '.xlsm',
  '.xlsb',
  '.xlt',
  '.xltx',
  '.odt',
  '.odp',
  '.ods',
])

const WORKSPACE_TEXT_EXTS = new Set([
  '.txt',
  '.log',
  '.lock',
  '.properties',
  '.conf',
  '.config',
  '.cfg',
  '.json',
  '.jsonc',
  '.json5',
  '.code-workspace',
  '.ipynb',
  '.js',
  '.jsx',
  '.ts',
  '.tsx',
  '.mts',
  '.cts',
  '.mjs',
  '.cjs',
  '.css',
  '.scss',
  '.less',
  '.html',
  '.htm',
  '.xml',
  '.yml',
  '.yaml',
  '.toml',
  '.ini',
  '.editorconfig',
  '.env',
  '.py',
  '.pyw',
  '.pyi',
  '.rs',
  '.go',
  '.java',
  '.c',
  '.cc',
  '.cpp',
  '.cxx',
  '.h',
  '.hpp',
  '.hh',
  '.hxx',
  '.ipp',
  '.cs',
  '.csx',
  '.php',
  '.phtml',
  '.rb',
  '.rake',
  '.gemspec',
  '.sh',
  '.bash',
  '.zsh',
  '.fish',
  '.bat',
  '.cmd',
  '.ps1',
  '.psm1',
  '.psd1',
  '.ps1xml',
  '.sql',
  '.csv',
  '.tsv',
  '.http',
  '.rest',
  '.graphql',
  '.gql',
  '.proto',
  '.prisma',
  '.sol',
  '.vue',
  '.svelte',
  '.astro',
  '.lua',
  '.kt',
  '.kts',
  '.ml',
  '.mli',
  '.fsscript',
  '.swift',
  '.dart',
  '.zig',
  '.nim',
  '.cr',
  '.r',
  '.jl',
  '.ex',
  '.exs',
  '.erl',
  '.hrl',
  '.erl',
  '.hrl',
  '.scala',
  '.sc',
  '.clj',
  '.cljs',
  '.cljc',
  '.edn',
  '.hs',
  '.lhs',
  '.ml',
  '.mli',
  '.fs',
  '.fsi',
  '.fsx',
  '.vb',
  '.vbs',
  '.m',
  '.mm',
  '.pl',
  '.pm',
  '.t',
  '.tcl',
  '.sv',
  '.svh',
  '.v',
  '.vh',
  '.gradle',
  '.groovy',
  '.gvy',
  '.hcl',
  '.tf',
  '.tfvars',
  '.bicep',
  '.cue',
  '.rego',
  '.asm',
  '.s',
  '.nim',
  '.nix',
  '.prisma',
  '.tex',
  '.xhtml',
  '.mod',
  '.sum',
  '.cshtml',
  '.razor',
  '.hbs',
  '.handlebars',
  '.mustache',
  '.liquid',
  '.twig',
  '.njk',
  '.pug',
  '.jade',
  '.sln',
  '.csproj',
  '.fsproj',
  '.vbproj',
  '.props',
  '.targets',
  '.xaml',
  '.gitignore',
  '.dockerignore',
])

const WORKSPACE_TEXT_FILE_NAMES = new Set([
  '.editorconfig',
  '.env',
  '.env.local',
  '.env.development',
  '.env.production',
  '.npmrc',
  '.nvmrc',
  '.yarnrc',
  '.prettierrc',
  '.eslintrc',
  '.babelrc',
  '.stylelintrc',
  '.browserslistrc',
  '.gitignore',
  '.dockerignore',
  '.gitattributes',
  '.gitmodules',
  'agents',
  'dockerfile',
  'containerfile',
  'compose.yaml',
  'compose.yml',
  'docker-compose.yaml',
  'docker-compose.yml',
  'makefile',
  'cmakelists.txt',
  'gemfile',
  'rakefile',
  'procfile',
  'justfile',
  'earthfile',
  'vagrantfile',
  'jenkinsfile',
  'brewfile',
  'pipfile',
  'poetry.lock',
  'cargo.lock',
  'go.mod',
  'go.sum',
  'readme',
  'license',
  'changelog',
  'authors',
  'contributors',
])

export function isWorkspaceTextLikeFile(lowerName: string, ext: string): boolean {
  return WORKSPACE_TEXT_EXTS.has(ext) || WORKSPACE_TEXT_FILE_NAMES.has(lowerName)
}

export function classifyWorkspaceFileSurface(lowerName: string, ext: string): WorkspaceFileSurface {
  if (WORKSPACE_IMAGE_EXTS.has(ext)) return 'imagePreview'
  if (WORKSPACE_PDF_EXTS.has(ext)) return 'pdfPreview'
  if (WORKSPACE_OFFICE_EXTS.has(ext)) return 'documentCard'
  if (WORKSPACE_MARKDOWN_EXTS.has(ext) || isWorkspaceTextLikeFile(lowerName, ext)) return 'builtinEditor'
  return 'sniffText'
}

export function previewLanguageForWorkspaceFile(lowerName: string, ext: string): string {
  return workspaceLanguageForFile(lowerName, ext)
}
