// Compatibility barrel for the renderer Local App API clients.
// Domain implementations live under ./api and existing imports stay stable.

export type { AgentProfileId } from '@littlesheep/prompt'
export type { PermissionModeId } from '../shared/permission-modes'
export type * from '../shared/attachment-contracts'
export type * from '../shared/memory-control-contracts'
export type * from '../shared/runtime-api-contracts'
export type * from '../shared/plugin-control-contracts'
export type * from '../shared/channel-control-contracts'
export type { HistoryMessageRecord as HistoryMessage } from '../shared/history-activity'
export type * from '../shared/session-project-contracts'
export type * from '../shared/workspace-contracts'
export * from './api/run'
export * from './api/sessions'
export * from './api/runtime'
export * from './api/attachments'
export * from './api/workspace'
export * from './api/extensions'
export * from './api/browser'
export * from './api/development-environments'
export * from './api/memory'
