// @littlesheep/harness - stages/reply.test.ts
import { describe, expect, it, vi } from 'vitest';
import { DEFAULT_BRANDING } from '@littlesheep/branding';
import { DEFAULT_CONFIG } from '@littlesheep/config';
import { textMessage } from '@littlesheep/types';
import { createMockLlm, makeCtx, textResponse } from '../tests/helpers.js';
import { createReplyStage } from './reply.js';

describe('replyStage', () => {
  it('includes the active Soul when composing the user-visible reply', async () => {
    const systemPrompts: string[] = [];
    const llm = createMockLlm((request) => {
      systemPrompts.push(String(request.messages[0]?.content ?? ''));
      return textResponse('带有人格风格的回复');
    });
    const stage = createReplyStage({
      llm,
      model: 'test',
      config: DEFAULT_CONFIG,
      branding: DEFAULT_BRANDING,
    });
    const ctx = makeCtx({
      inbound: textMessage('user', '你好'),
      bootstrap: { 'SOUL.md': 'SOUL_SENTINEL_REPLY_VOICE' },
    });

    const result = await stage(ctx);

    expect(result.next).toBe('finalize');
    expect(ctx.reply).toBe('带有人格风格的回复');
    expect(llm.chat).toHaveBeenCalledTimes(1);
    expect(systemPrompts[0]).toContain('SOUL_SENTINEL_REPLY_VOICE');
    expect(ctx.replyProvenance).toMatchObject({ source: 'llm', purpose: 'reply', rewriteCount: 0 });
  });

  it('buffers streaming output and publishes only the distinct rewritten reply', async () => {
    const llm = createMockLlm([
      textResponse('还是同一句回复。'),
      textResponse('这次换一种自然的说法。'),
    ]);
    const stage = createReplyStage({
      llm,
      model: 'test',
      config: DEFAULT_CONFIG,
      branding: DEFAULT_BRANDING,
    });
    const deltas: string[] = [];
    const ctx = makeCtx({
      inbound: textMessage('user', '再说一次'),
      history: [textMessage('assistant', '还是同一句回复。')],
    });
    ctx.onAssistantDelta = (delta) => deltas.push(delta);

    const result = await stage(ctx);

    expect(result.ok).toBe(true);
    expect(ctx.reply).toBe('这次换一种自然的说法。');
    expect(deltas).toEqual(['这次换一种自然的说法。']);
    expect(ctx.replyProvenance?.rewriteCount).toBe(1);
  });

  it('returns a runtime error instead of publishing a repeated fallback', async () => {
    const llm = createMockLlm(textResponse('固定回复'));
    const stage = createReplyStage({
      llm,
      model: 'test',
      config: DEFAULT_CONFIG,
      branding: DEFAULT_BRANDING,
    });
    const deltas: string[] = [];
    const ctx = makeCtx({
      history: [textMessage('assistant', '固定回复')],
      inbound: textMessage('user', '继续'),
    });
    ctx.onAssistantDelta = (delta) => deltas.push(delta);

    const result = await stage(ctx);

    expect(result.ok).toBe(false);
    expect(result.error).toMatch(/repeated a previously published reply/);
    expect(ctx.reply).toBeUndefined();
    expect(deltas).toEqual([]);
    expect(llm.chat).toHaveBeenCalledTimes(3);
  });

  it('rewrites a duplicate found only in the durable session registry', async () => {
    const llm = createMockLlm([
      textResponse('Archived exact reply'),
      textResponse('Fresh model-authored wording'),
    ]);
    const stage = createReplyStage({
      llm,
      model: 'test',
      config: DEFAULT_CONFIG,
      branding: DEFAULT_BRANDING,
    });
    const ctx = makeCtx({
      history: [],
      inbound: textMessage('user', 'Repeat the old question'),
    });
    ctx.reserveUserFacingReply = vi.fn(async (reply: string) => reply !== 'Archived exact reply');

    const result = await stage(ctx);

    expect(result.ok).toBe(true);
    expect(ctx.reply).toBe('Fresh model-authored wording');
    expect(ctx.replyProvenance?.rewriteCount).toBe(1);
    expect(ctx.reserveUserFacingReply).toHaveBeenCalledTimes(2);
  });

  it('fails closed when the durable reply registry cannot reserve text', async () => {
    const llm = createMockLlm(textResponse('Response generated by the Provider API'));
    const stage = createReplyStage({
      llm,
      model: 'test',
      config: DEFAULT_CONFIG,
      branding: DEFAULT_BRANDING,
    });
    const deltas: string[] = [];
    const ctx = makeCtx({ inbound: textMessage('user', 'Hello') });
    ctx.reserveUserFacingReply = vi.fn(async () => {
      throw new Error('registry unavailable');
    });
    ctx.onAssistantDelta = (delta) => deltas.push(delta);

    const result = await stage(ctx);

    expect(result.ok).toBe(false);
    expect(result.error).toContain('registry unavailable');
    expect(ctx.reply).toBeUndefined();
    expect(deltas).toEqual([]);
  });
});
